name: deploy-doc
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: config git
        run: git config user.name github-actions && git config user.email github-actions@github.com

      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
        
      - run: pip install -e ".[dev]"
      
      - name: build dev doc
        run: |
          cd docs
          mike deploy dev --push
