name: deploy-doc
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pwd
      - run: ls -la
      - run: pip install -e ".[dev]"

      - name: build dev doc
        run: |
          cd docs
          mike deploy dev --push
